
development:
  address: <%='[MAILGUN_SMTP_SERVER]'%>
  port: <%='[MAILGUN_SMTP_PORT]'%>
  domain: <%=ENV['MAILGUN_DOMAIN']%>
  authentication: "plain"
  user_name: <%=ENV['MAILGUN_SMTP_LOGIN']%>
  password: <%=ENV['MAILGUN_SMTP_PASSWORD']%>
  enable_starttls_auto: true
production:
  address: <%=ENV['MAILGUN_SMTP_SERVER']%>
  port: <%=ENV['MAILGUN_SMTP_PORT']%>
  domain: <%=ENV['MAILGUN_DOMAIN']%>
  authentication: "plain"
  user_name: <%=ENV['MAILGUN_SMTP_LOGIN']%>
  password: <%=ENV['MAILGUN_SMTP_PASSWORD']%>
  enable_starttls_auto: true